function [ dhdx ] = terrainGradientY( terrain, X, Y )
%TERRAINGRADIENTY 
%               Returns the gradient in the y direction at each point in (X,Y)
%               terrain: a terrain structure generated by the
%                           generateTerrain() function.
%                   X,Y: querry points to find the 
% 
%               If X and Y are matrices
%                   dhdx(i,j) is the height at X(i,j), Y(i,j)
%                   This consides with the convention used for meshgrid.


% complex step differentiation. Better numerical propreties then finite
% difference.

h = 1E-9;

dhdx = imag(terrainHeight(terrain, X , Y+ 1i*h) - terrainHeight(terrain, X , Y- 1i*h))/2/h;


end

